services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - rabbitmq
    network_mode: "host"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15672:15672
